### ISSUE TITLE
opt-in/opt-out

### ISSUE THREAD

**Issue by ffaf1** [d-damien/flarum-ext-contact-request#1]
User question: does this plugin provide a way to opt-out (or opt-in) this feature?

**Comment by d-damien** [comment]
Yes it does :)
In the standard *Notifications* settings : "A member requests to contact you"

**Comment by d-damien** [comment]
It is missing a thing or two (link not taking full button surface, forgot to rebuild js assets, not very extensible) but it works. Still marked as WIP for my defense :p

**Comment by ffaf1** [comment]
Very good and thanks for this useful extension!

**Comment by d-damien** [comment]
Self-reminder : it would be nice to hide the button (currently it just blocks notifications).
